### ISSUE TITLE
Unable to Create Issue Type Bug with TechTalk.JiraRestClient CreateIssue Method

### ISSUE THREAD

**Issue by sndadi** [techtalk/JiraRestClient#40]
creating jira bug with TechTalk.JiraRestClient : {"errorMessages":[],"errors":{"timetracking":"Field 'timetracking' cannot be set. It is not on the appropriate screen, or unknown."}}

**Comment by albracko** [comment]
sndadi...this is not a bug in the TechTalk.JiraRestClient...it's the limitiation of JIRA REST API

you are trying to create an issue with a field where the JIRA project itself doesn't have a field available if you create an issue through browser.

To explain it...when you create an issue through JIRA REST API you can only set fields which are available on Create Issue page. 
So if you open your JIRA home page, and click on Create link and select the project in which you would like to create an issue you have x number of fields you can set in your browser (like IssueType, Assignee, Priority etc.)...so through API, you can also set just those fields and nothing more.

So if you would like to set TimeTracking on creation of JIRA, then you have to open JIRA Administrators page and modify the Create Issue screen and add this filed to this screen...otherwise JIRA REST API won't let you set it. ;)
